stages:
  - start server
  - unit-test

# image: docker:git

services:
  - docker:dind

run test server:
  before_script:
    - docker build -t nodeserver ./server 

  stage: start server 

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - docker run -d --name nodeserver -p 3000:3000 nodeserver

run unit test:
  image : node:12.7.0-alpine

  before_script:
    - npm i -D

  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run production-test