stages:
  - unit-test
  - deploy

image: node:12.7.0-alpine

run test server:

  before_script:
    - npm install 
    - npm run start:dev & 
    
  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run production-test

run deploy:
  stage : deploy
  before_script : 
    - sudo apt-get install git
  script: git push production HEAD:master
  environment:
    name: kyronus-env