stages:
  - unit-test
  - deploy

image: node:10.16.3-alpine

run test server:
  cache:
    untracked : true

  before_script:
    - npm install 
    - npm run start:dev & 
    
  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run production-test
