stages:
  - unit-test
  - deploy

image: node:latest

run test server:
  cache:
    untracked : true

  before_script:
    - npm install 
    - npm run ci-start-server &
    
  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run ci-test
