stages:
  - unit-test

image: node:12.7.0-alpine

run test server:

  before_script:
    - npm install 
    - npm run start:dev & 
    
  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run production-test