stages:
  - unit-test

image: node:12.7.0-alpine

run test server:
  before_script:
    - npm install
  stage: start server 
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - npm run start:dev


run unit test:
  stage: unit-test
  cache:
    untracked: true
    policy: pull
  only:
    - master
  script:
    - npm run test