stages:
  - unit-test
  - deploy

image: node:12.7.0-alpine

run test server:
  cache:
    untracked : true

  before_script:
    - npm install 
    - npm run start:dev & 
    
  stage: unit-test

  cache:
    untracked: true
    policy: pull

  only:
    - master

  script:
    - npm run production-test

run deploy:
  image : alpine:3.7
  stage : deploy
  before_script :
    - apk add --no-cache git
  script: 
    - helm --help
  environment:
    name: kyronus-env
    url: https://citychaserstudio.com
