version: "3.7"
services: 
    node:
      build: ./server
      ports:
            - "3000"  
    # node2:
    #   build: ./server
    #   ports:
    #         - "3000"  
    #   networks:
    #         - app-network
    # node3:
    #   build: ./server
    #   ports:
    #         - "3000"   
    #   networks: 
    #         - app-network
    nginx:
      build: ./nginx
      links:
            - node   
      ports:
            - "80:80"